[providers]
op = "inject_secrets.providers.onepassword:OnePasswordProvider"
bw = "inject_secrets.providers.bitwarden:BitwardenCliProvider"
toml = "inject_secrets.providers.toml:TomlProvider"

[provider_config]
toml = { file = "secrets.toml" }

